# Generated by Django 4.1.7 on 2023-02-25 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancel',
            name='order',
        ),
        migrations.RemoveField(
            model_name='confirms',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='confirms',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='product',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='reject',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='reject',
            name='order',
        ),
        migrations.RemoveField(
            model_name='samplesale',
            name='product',
        ),
        migrations.RemoveField(
            model_name='send',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='send',
            name='order',
        ),
        migrations.RemoveField(
            model_name='transfers',
            name='order',
        ),
        migrations.AddField(
            model_name='products',
            name='detail',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.DeleteModel(
            name='Accepts',
        ),
        migrations.DeleteModel(
            name='Cancel',
        ),
        migrations.DeleteModel(
            name='Confirms',
        ),
        migrations.DeleteModel(
            name='Customers',
        ),
        migrations.DeleteModel(
            name='Employees',
        ),
        migrations.DeleteModel(
            name='OrderDetails',
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
        migrations.DeleteModel(
            name='Reject',
        ),
        migrations.DeleteModel(
            name='Samplesale',
        ),
        migrations.DeleteModel(
            name='Send',
        ),
        migrations.DeleteModel(
            name='Transfers',
        ),
    ]
